spring.application.name=fintrack

# spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
# spring.datasource.username=postgres
# spring.datasource.password=Asfak@2001
spring.datasource.url=jdbc:postgresql://ep-curly-sunset-attvfm1x-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_9JrwaqSd8IRT&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9JrwaqSd8IRT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
# server.port=8080
server.port=${PORT:8080}